name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test (stable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --all --verbose
      - name: Test
        run: cargo test --verbose

  build-beta:
    name: Build and Test (beta)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust beta
        uses: dtolnay/rust-toolchain@beta
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --all --verbose
      - name: Test
        run: cargo test --verbose

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || (secrets.ALGOLIA_APP_ID != '' && secrets.ALGOLIA_API_KEY != '') }}
    env:
      APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Run integration tests
        run: cargo test -- --ignored --nocapture


